name: Deploy and Upload Data

on:
  push:
    branches: [ main ]
jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
              
    
      - name: Create-Environment
        run: make create-environment
      - name: Install Modules
        run: make dev-setup
